name: C++ Build

on:
  push: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: actions-setup-cmake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.22.x'

      - name: Build C++ program
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_CXX_STANDARD=20 ..
          cmake --build .  # Use CMake to build the project

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: clip-${{ matrix.os }}
          path: build/bin/main*
